## Summary

The purpose of this notebook is to process the ALA Yearly Occurrences Data for Wildlife Seminary Feature 7 (Animal Timeline Comparisons).

Data already includes conservation status and latitude/longitude joined onto yearly occurrences.

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 10000)

### Reading in Processed Data

In [2]:
df = pd.read_csv("wildlife_occurrences_with_location_end_status_v2_w_lat_long.csv")

In [3]:
display(df.head())
df.shape

,year,stateTerritory,ibraRegion,ScientificName,CommonName,Kingdom,griisStatus,capadStatus,EPBCThreatStatus,occurrenceCount,IBRA_REG_N,STATE,lat,lon,CommonName_clean
0,1900,NSW,Australian Alps,Ornithorhynchus anatinus,Platypus,Animalia,Native,PA,Present,1,Australian Alps,NSW,-36.074960,148.469095,Platypus
1,1900,NSW,Australian Alps,Pseudophryne corroboree,Southern Corroboree Frog,Animalia,Native,PA,Critically Endangered,6,Australian Alps,NSW,-36.074960,148.469095,Southern Corroboree Frog
2,1900,NSW,Brigalow Belt South,Ardeotis australis,Australian Bustard,Animalia,Native,not protected,Present,2,Brigalow Belt South,NSW,-30.762574,149.581615,Australian Bustard
3,1900,NSW,Brigalow Belt South,Chlamydera maculata,Spotted Bowerbird,Animalia,Native,not protected,Present,1,Brigalow Belt South,NSW,-30.762574,149.581615,Spotted Bowerbird
4,1900,NSW,Brigalow Belt South,Hemiaspis damelii,Grey Snake,Animalia,Native,not protected,Endangered,3,Brigalow Belt South,NSW,-30.762574,149.581615,Grey Snake

(458419, 15)

### Starting from 1970

In [4]:
df = df.query("year >= 1970 ").reset_index(drop = True)

# remove extra column
df = df.drop("CommonName", axis = 1)

In [5]:
df.head()

,year,stateTerritory,ibraRegion,ScientificName,Kingdom,griisStatus,capadStatus,EPBCThreatStatus,occurrenceCount,IBRA_REG_N,STATE,lat,lon,CommonName_clean
0,1970,ACT,Australian Alps,Nyctophilus gouldi,Animalia,Native,PA,Present,1,Australian Alps,ACT,-35.667875,148.909459,Gould's Long-eared Bat
1,1970,ACT,South Eastern Highlands,Aythya australis,Animalia,Native,PA,Present,2,South Eastern Highlands,ACT,-35.434530,149.030591,Hardhead
2,1970,ACT,South Eastern Highlands,Chloebia gouldiae,Animalia,Native,not protected,Endangered,1,South Eastern Highlands,ACT,-35.434530,149.030591,Gouldian Finch
3,1970,ACT,South Eastern Highlands,Chroicocephalus novaehollandiae,Animalia,Native,PA,Present,1,South Eastern Highlands,ACT,-35.434530,149.030591,Silver Gull
4,1970,ACT,South Eastern Highlands,Chroicocephalus novaehollandiae,Animalia,Native,not protected,Present,2,South Eastern Highlands,ACT,-35.434530,149.030591,Silver Gull

In [9]:
df.head()

,year,stateTerritory,ibraRegion,ScientificName,Kingdom,griisStatus,capadStatus,EPBCThreatStatus,occurrenceCount,IBRA_REG_N,STATE,lat,lon,CommonName_clean
0,1970,ACT,Australian Alps,Nyctophilus gouldi,Animalia,Native,PA,Present,1,Australian Alps,ACT,-35.667875,148.909459,Gould's Long-eared Bat
1,1970,ACT,South Eastern Highlands,Aythya australis,Animalia,Native,PA,Present,2,South Eastern Highlands,ACT,-35.434530,149.030591,Hardhead
2,1970,ACT,South Eastern Highlands,Chloebia gouldiae,Animalia,Native,not protected,Endangered,1,South Eastern Highlands,ACT,-35.434530,149.030591,Gouldian Finch
3,1970,ACT,South Eastern Highlands,Chroicocephalus novaehollandiae,Animalia,Native,PA,Present,1,South Eastern Highlands,ACT,-35.434530,149.030591,Silver Gull
4,1970,ACT,South Eastern Highlands,Chroicocephalus novaehollandiae,Animalia,Native,not protected,Present,2,South Eastern Highlands,ACT,-35.434530,149.030591,Silver Gull

### Aggregating Datasets for Animal Counts by Year, State, EPBCThreat Status, Kingdom

In [35]:
agg_cols = ["year","stateTerritory","ScientificName", "CommonName_clean", "EPBCThreatStatus"]

df_agg = (df.groupby(agg_cols).
 agg({"occurrenceCount": "sum"})).reset_index().rename(columns = {"CommonName_clean": "CommonName"})

In [36]:
df_agg.head()

,year,stateTerritory,ScientificName,CommonName,EPBCThreatStatus,occurrenceCount
0,1970,ACT,Aythya australis,Hardhead,Present,2
1,1970,ACT,Chloebia gouldiae,Gouldian Finch,Endangered,1
2,1970,ACT,Chroicocephalus novaehollandiae,Silver Gull,Present,3
3,1970,ACT,Eulamprus heatwolei,Yellow-bellied /water-skink,Present,1
4,1970,ACT,Maccullochella macquariensis,Trout Cod,Endangered,1

In [39]:
# converting to csv
df_agg.to_csv("epic_6_agg_wildlife_occurrences_1970_2022.csv")

### Sample Query

In [37]:
schema = "placeholder"
table = "placeholder"


### Creating Table

create_query = f"""

CREATE TABLE {table} (
    year INT,
    stateTerritory VARCHAR(50),
    ScientificName VARCHAR(255),
    CommonName VARCHAR(255),
    EPBCThreatStatus VARCHAR(50),
    occurrenceCount INT
);

"""

### Creating Dataset with Names and Wikipedia Link

In [42]:
top_animals_df = pd.read_csv("animal_details_top_animals.csv")
top_animals_df = top_animals_df[["CommonName", "ScientificName", "occurrenceCount"]]

In [43]:
top_animals_df

,CommonName,ScientificName,occurrenceCount
0,"Rabbit, European Rabbit",Oryctolagus cuniculus,5754
1,"Red Fox, Fox",Vulpes vulpes,5485
2,Koala,Phascolarctos cinereus,4897
3,Eastern Grey Kangaroo,Macropus giganteus,3734
4,Swamp Wallaby,Wallabia bicolor,3199
5,Short-beaked Echidna,Tachyglossus aculeatus,2894
6,Western Grey Kangaroo,Macropus fuliginosus,2280
7,"Bare-nosed Wombat, Common Wombat",Vombatus ursinus,1856
8,Platypus,Ornithorhynchus anatinus,1337
9,Southern Long-nosed Bandicoot,Perameles nasuta,1267
10,Greater Bilby,Macrotis lagotis,1120
11,Gang-gang Cockatoo,Callocephalon fimbriatum,1025
12,Agile Antechinus,Antechinus agilis,690
13,Bush Stone-curlew,Burhinus grallarius,671
14,Greater Glider (southern and central),Petauroides volans,646
15,Yellow-footed Antechinus,Antechinus flavipes,620
16,Rainbow Bee-eater,Merops ornatus,604
17,White-bellied Sea-Eagle,Haliaeetus leucogaster,593
18,Glossy Black-Cockatoo,Calyptorhynchus lathami,586
19,Burrowing Bettong,Bettongia lesueur,577
20,Grey-headed Flying-fox,Pteropus poliocephalus,547
21,Yellow-bellied Glider,Petaurus australis,478
22,Brown Treecreeper,Climacteris picumnus,437
23,Flame Robin,Petroica phoenicea,414
24,Pied Oystercatcher,Haematopus longirostris,397
25,Australian Shelduck,Tadorna tadornoides,396
26,Southern Brown Bandicoot,Isoodon obesulus,368
27,Apostlebird,Struthidea cinerea,366
28,Red-tailed Black-Cockatoo,Calyptorhynchus banksii,353
29,Hardhead,Aythya australis,340
30,Grey-crowned Babbler,Pomatostomus temporalis,326
31,Eastern Pygmy-possum,Cercartetus nanus,323
32,Magpie Goose,Anseranas semipalmata,318
33,Blue-billed Duck,Oxyura australis,313
34,Osprey,Pandion haliaetus,302
35,Cattle Egret,Bubulcus ibis,301
36,Little Egret,Egretta garzetta,279
37,"Long-haired Rat, Mayaroo",Rattus villosissimus,270
38,Pacific Gull,Larus pacificus,252
39,White-fronted Chat,Epthianura albifrons,250
40,Powerful Owl,Ninox strenua,243
41,Rufous Fantail,Rhipidura rufifrons,240
42,Varied Sittella,Daphoenositta chrysoptera,234
43,Superb Parrot,Polytelis swainsonii,227
44,Squirrel Glider,Petaurus norfolcensis,220
45,Sooty Oystercatcher,Haematopus fuliginosus,210
46,Comb-crested Jacana,Irediparra gallinacea,208
47,Little Eagle,Hieraaetus morphnoides,202
48,Tasmanian Pademelon,Thylogale billardierii,199
49,Diamond Firetail,Stagonopleura guttata,190
50,Wompoo Fruit-Dove,Ptilinopus magnificus,189
51,Peregrine Falcon,Falco peregrinus,172
52,Great Crested Grebe,Podiceps cristatus,165
53,Square-tailed Kite,Lophoictinia isura,162
54,Red-legged Pademelon,Thylogale stigmatica,161
55,Hooded Robin,Melanodryas cucullata,153
56,Pilotbird,Pycnoptilus floccosus,153
57,Diamond Dove,Geopelia cuneata,145
58,Brush-tailed Phascogale,Phascogale tapoatafa,143
59,Black-faced Monarch,Monarcha melanopsis,136
60,Southern Cassowary,Casuarius casuarius,134
61,"New Holland Mouse, Pookila",Pseudomys novaehollandiae,124
62,Australian Bustard,Ardeotis australis,113
63,Grey Goshawk,Accipiter novaehollandiae,110
64,Feathertail Glider,Acrobates pygmaeus,109
65,Kelp Gull,Larus dominicanus,106
66,Turquoise Parrot,Neophema pulchella,105
67,Long-nosed Potoroo,Potorous tridactylus,96
68,"Little Bent-winged Bat, Little Bent-wing Bat",Miniopterus australis,93
69,Southern Whiteface,Aphelocephala leucopsis,88
70,White-winged Triller,Lalage tricolor,88
71,"Large-eared Pied Bat, Large Pied Bat",Chalinolobus dwyeri,87
72,Long-footed Potoroo,Potorous longipes,83
73,"Spotted-tailed Quoll, Tiger Quol",Dasyurus maculatus,80
74,Red-necked Stint,Calidris ruficollis,79
75,Eastern Horseshoe-bat,Rhinolophus megaphyllus,78
76,Rose-crowned Fruit-Dove,Ptilinopus regina,78
77,Olive Whistler,Pachycephala olivacea,76
78,Spotted Harrier,Circus assimilis,76
79,"Long-nosed Fur-seal, New Zealand Fur-seal",Arctocephalus forsteri,75
80,Southern Emu-wren,Stipiturus malachurus,74
81,Bar-tailed Godwit,Limosa lapponica,71
82,Leadbeater's Possum,Gymnobelideus leadbeateri,71
83,Pink Robin,Petroica rodinogaster,71
84,Swift Parrot,Lathamus discolor,70
85,Malleefowl,Leipoa ocellata,69
86,Sooty Owl,Tyto tenebricosa,69
87,White-throated Needletail,Hirundapus caudacutus,69
88,"Bridled Nail-tail Wallaby, Bridled Nailtail Wa...",Onychogalea fraenata,65
89,Blue-winged Parrot,Neophema chrysostoma,64
90,Little Penguin,Eudyptula minor,63
91,Crested Bellbird,Oreoica gutturalis,62
92,Eastern Barred Bandicoot,Perameles gunnii,62
93,Satin Flycatcher,Myiagra cyanoleuca,62
94,"Australian Fur-seal, Australo-African Fur-seal",Arctocephalus pusillus,61
95,"Pale Field-rat, Djini",Rattus tunneyi,61
96,Brush-tailed Rock-wallaby,Petrogale penicillata,59
97,Plains-wanderer,Pedionomus torquatus,58
98,Humpback Whale,Megaptera novaeangliae,57
99,Rufous Bettong,Aepyprymnus rufescens,57
100,Spectacled Flying-fox,Pteropus conspicillatus,57
101,White-footed Dunnart,Sminthopsis leucopus,56
102,Barking Owl,Ninox connivens,55
103,"Common Greenshank, Greenshank",Tringa nebularia,55
104,Black-faced Cormorant,Phalacrocorax fuscescens,54
105,Squatter Pigeon,Geophaps scripta,54
106,"Latham's Snipe, Japanese Snipe",Gallinago hardwickii,53
107,Southern Scrub-robin,Drymodes brunneopygia,51
108,"Kowari, brushy-tailed marsupial rat, Byrne's c...",Dasyuroides byrnei,50
109,"Large-footed Myotis, Southern Myotis",Myotis macropus,50
110,Australasian Gannet,Morus serrator,48
111,Eastern Bristlebird,Dasyornis brachypterus,48
112,Masked Owl,Tyto novaehollandiae,48
113,"Brush-tailed Bettong, Woylie",Bettongia penicillata,47
114,Gould's Long-eared Bat,Nyctophilus gouldi,47
115,Rufous Scrub-bird,Atrichornis rufescens,44
116,Common Sandpiper,Actitis hypoleucos,43
117,Double-eyed Fig-Parrot,Cyclopsitta diophthalma,43
118,Sharp-tailed Sandpiper,Calidris acuminata,43
119,Purple-gaped Honeyeater,Lichenostomus cratitius,42
120,"Red-tailed Phascogale, Red-tailed Wambenger, K...",Phascogale calura,42
121,Striated Fieldwren,Calamanthus fuliginosus,42
122,Whiskered Tern,Chlidonias hybrida,42
123,Curlew Sandpiper,Calidris ferruginea,41
124,Black-necked Stork,Ephippiorhynchus asiaticus,40
125,Spotted Bowerbird,Chlamydera maculata,39
126,"Australian Sea-lion, Australian Sea Lion",Neophoca cinerea,38
127,Ruddy Turnstone,Arenaria interpres,37
128,Lewin's Rail,Lewinia pectoralis,34
129,Pacific Golden Plover,Pluvialis fulva,34
130,"Hastings River Mouse, Koontoo",Pseudomys oralis,33
131,Redthroat,Pyrrholaemus brunneus,32
132,Shy Heathwren,Hylacola cauta,32
133,Rufous Bristlebird,Dasyornis broadbenti,31
134,"Tasmanian Bettong, Eastern Bettong",Bettongia gaimardi,31
135,Whimbrel,Numenius phaeopus,31
136,"Eastern Curlew, Far Eastern Curlew",Numenius madagascariensis,30
137,Barred Cuckoo-shrike,Coracina lineata,29
138,Black Falcon,Falco subniger,28
139,Southern Right Whale,Eubalaena australis,27
140,Double-banded Plover,Charadrius bicinctus,25
141,Numbat,Myrmecobius fasciatus,25
142,Black-breasted Buzzard,Hamirostra melanosternon,24
143,Cotton Pygmy-goose,Nettapus coromandelianus,24
144,"Broad-toothed Rat, Tooarrana",Mastacomys fuscus,23
145,"Marsh Sandpiper, Little Greenshank",Tringa stagnatilis,23
146,"Pale-vented Bush-hen, Bush-hen",Amaurornis moluccana,23
147,Quokka,Setonix brachyurus,23
148,Black Noddy,Anous minutus,22
149,"Indian Ocean Bottlenose Dolphin, Spotted Bottl...",Tursiops aduncus,22
150,Western Pygmy-possum,Cercartetus concinnus,22
151,Terek Sandpiper,Xenus cinereus,20
152,Yellow-bellied Sheathtail-bat,Saccolaimus flaviventris,20
153,Albert's Lyrebird,Menura alberti,19
154,"Eastern Falsistrelle, Eastern False Pipistrelle",Falsistrellus tasmaniensis,19
155,Great Knot,Calidris tenuirostris,19
156,Greater Broad-nosed Bat,Scoteanax rueppellii,19
157,Poonta,Pseudomys bolami,19
158,White-browed Treecreeper,Climacteris affinis,19
159,Chestnut-rumped Heathwren,Hylacola pyrrhopygia,18
160,"Mitchell's Hopping-mouse, Pankot",Notomys mitchellii,18
161,Red-backed Button-quail,Turnix maculosus,18
162,Australasian Bittern,Botaurus poiciloptilus,17
163,Chestnut Quail-thrush,Cinclosoma castanotum,17
164,Superb Fruit-Dove,Ptilinopus superbus,17
165,Collared Kingfisher,Todiramphus chloris,16
166,Eastern Ground Parrot,Pezoporus wallicus,16
167,"Eastern Quoll, Luaner",Dasyurus viverrinus,16
168,Rufous Fieldwren,Calamanthus campestris,16
169,Wood Sandpiper,Tringa glareola,16
170,Eastern Cave Bat,Vespadelus troughtoni,15
171,Mountain Pygmy-possum,Burramys parvus,15
172,Pied Honeyeater,Certhionyx variegatus,15
173,"Queensland Tube-nosed Bat, Eastern Tube-nosed Bat",Nyctimene robinsoni,15
174,Black-tailed Godwit,Limosa limosa,14
175,Red-lored Whistler,Pachycephala rufogularis,14
176,Flock Bronzewing,Phaps histrionica,13
177,Gilbert's Whistler,Pachycephala inornata,13
178,Lemuroid Ringtail Possum,Hemibelideus lemuroides,13
179,Sanderling,Calidris alba,13
180,Stripe-faced Dunnart,Sminthopsis macroura,13
181,Banded Stilt,Cladorhynchus leucocephalus,12
182,Fluttering Shearwater,Puffinus gavia,12
183,"Red Knot, Knot",Calidris canutus,12
184,White Tern,Gygis alba,12
185,Buff-sided Robin,Poecilodryas cerviniventris,11
186,Fork-tailed Swift,Apus pacificus,11
187,"Oriental Plover, Oriental Dotterel",Charadrius veredus,11
188,Oriental Pratincole,Glareola maldivarum,11
189,Palm Cockatoo,Probosciger aterrimus,11
190,Striated Grasswren,Amytornis striatus,11
191,Common Noddy,Anous stolidus,10
192,"Eastern Blossom Bat, Queensland Blossom Bat",Syconycteris australis,10
193,Golden-tipped Bat,Phoniscus papuensis,10
194,Red-chested Button-quail,Turnix pyrrhothorax,10
195,Common Tern,Sterna hirundo,9
196,Eastern Grass Owl,Tyto longimembris,9
197,"Lesser Frigatebird, Least Frigatebird",Fregata ariel,9
198,Marbled Frogmouth,Podargus ocellatus,9
199,Red-tailed Tropicbird,Phaethon rubricauda,9
200,Black Bittern,Ixobrychus flavicollis,8
201,"Eastern Chestnut Mouse, Karrooka",Pseudomys gracilicaudatus,8
202,"Oriental Cuckoo, Horsfield's Cuckoo",Cuculus optatus,8
203,Purple-crowned Fairy-wren,Malurus coronatus,8
204,Radjah Shelduck,Tadorna radjah,8
205,Blue-faced Parrot-Finch,Erythrura trichroa,7
206,Little Pied Bat,Chalinolobus picatus,7
207,Northern Bettong,Bettongia tropica,7
208,Painted Honeyeater,Grantiella picta,7
209,Southern Royal Albatross,Diomedea epomophora,7
210,"White-winged Tern, White-winged Black Tern",Chlidonias leucopterus,7
211,Brown Booby,Sula leucogaster,6
212,Freckled Duck,Stictonetta naevosa,6
213,Ghost Bat,Macroderma gigas,6
214,Ground Cuckoo-shrike,Coracina maxima,6
215,King Penguin,Aptenodytes patagonicus,6
216,Partridge Pigeon,Geophaps smithii,6
217,"Silky Mouse, Nalpo",Pseudomys apodemoides,6
218,Slender-billed Thornbill,Acanthiza iredalei,6
219,Swamp Antechinus,Antechinus minimus,6
220,Forty-spotted Pardalote,Pardalotus quadragintus,5
221,Grey Falcon,Falco hypoleucos,5
222,Hall's Babbler,Pomatostomus halli,5
223,Inland Forest Bat,Vespadelus baverstocki,5
224,"Mount Claro Rock Wallaby, Sharman's Rock Wallaby",Petrogale sharmani,5
225,"Sandy Inland Mouse, Mingkiri",Pseudomys hermannsburgensis,5
226,Western Grasswren,Amytornis textilis,5
227,Western Whipbird,Psophodes nigrogularis,5
228,Common Planigale,Planigale maculata,4
229,Dugong,Dugong dugon,4
230,Gentoo Penguin,Pygoscelis papua,4
231,"Kultarr, Eastern Kultarr",Antechinomys laniger,4
232,Mallee Emu-wren,Stipiturus mallee,4
233,Masked Booby,Sula dactylatra,4
234,"Northern Quoll, Digul [Gogo-Yimidir], Wijingad...",Dasyurus hallucatus,4
235,Orange Leaf-nosed Bat,Rhinonicteris aurantia,4
236,Providence Petrel,Pterodroma solandri,4
237,Purple-necked Rock-wallaby,Petrogale purpureicollis,4
238,Red Goshawk,Erythrotriorchis radiatus,4
239,Sandhill Dunnart,Sminthopsis psammophila,4
240,Shy Albatross,Thalassarche cauta,4
241,Yellow Chat,Epthianura crocea,4
242,Black-naped Tern,Sterna sumatrana,3
243,Black-winged Monarch,Monarcha frater,3
244,"Chuditch, Western Quoll",Dasyurus geoffroii,3
245,"Common Dolphin, Short-beaked Common Dolphin",Delphinus delphis,3
246,"Desert Mouse, Wildjin",Pseudomys desertor,3
247,Eastern Long-eared Bat,Nyctophilus bifax,3
248,Fairy Prion,Pachyptila turtur,3
249,"Forrests Mouse, Anoola",Leggadina forresti,3
250,Grey Plover,Pluvialis squatarola,3
251,"Little Curlew, Little Whimbrel",Numenius minutus,3
252,"Noisy Scrub-bird, Tjimiluk",Atrichornis clamosus,3
253,Southern Elephant Seal,Mirounga leonina,3
254,Southern Hairy-nosed Wombat,Lasiorhinus latifrons,3
255,Tasmanian Devil,Sarcophilus harrisii,3
256,Antipodean Albatross,Diomedea antipodensis,2
257,Barn Swallow,Hirundo rustica,2
258,Bennett's Tree-kangaroo,Dendrolagus bennettianus,2
259,Carpentarian Grasswren,Amytornis dorotheae,2
260,"Fawn Hopping-mouse, Ooarri",Notomys cervinus,2
261,"Greater Sand Plover, Large Sand Plover",Charadrius leschenaultii,2
262,"Killer Whale, Orca",Orcinus orca,2
263,"Lesser Sand Plover, Mongolian Plover",Charadrius mongolus,2
264,Orange-bellied Parrot,Neophema chrysogaster,2
265,Pygmy Sperm Whale,Kogia breviceps,2
266,Roseate Tern,Sterna dougallii,2
267,Yellow-footed Rock-wallaby,Petrogale xanthopus,2
268,Black-breasted Button-quail,Turnix melanogaster,1
269,Black-eared Miner,Manorina melanotis,1
270,"Black-footed Tree-rat, Djintamoonga",Mesembriomys gouldii,1
271,Black-winged Petrel,Pterodroma nigripennis,1
272,"Blainville's Beaked Whale, Dense-beaked Whale",Mesoplodon densirostris,1
273,"Canefield Rat, Minkala",Rattus sordidus,1
274,"Coastal Sheath-tailed Bat, North-eastern Sheat...",Taphozous australis,1
275,Common Diving-Petrel,Pelecanoides urinatrix,1
276,Dwarf Sperm Whale,Kogia sima,1
277,Eastern Hare-wallaby,Lagorchestes leporides,1
278,Hoary Wattled Bat,Chalinolobus nigrogriseus,1
279,Leopard Seal,Hydrurga leptonyx,1
280,Little Shearwater,Puffinus assimilis,1
281,Long-tailed Dunnart,Sminthopsis longicaudata,1
282,Mahogany Glider,Petaurus gracilis,1
283,Paucident Planigale,Planigale gilesi,1
284,Red-footed Booby,Sula sula,1
285,"Southern Giant-Petrel, Southern Giant Petrel",Macronectes giganteus,1
286,"Strap-toothed Beaked Whale, Strap-toothed Whal...",Mesoplodon layardii,1
287,Subantarctic Fur-seal,Arctocephalus tropicalis,1
288,Western Bristlebird,Dasyornis longirostris,1
289,White-faced Storm-Petrel,Pelagodroma marina,1
290,White-tailed Tropicbird,Phaethon lepturus,1
291,"Wopilkara, Greater Stick-nest Rat",Leporillus conditor,1

In [44]:
import urllib.parse

# Create a Wikipedia link column
top_animals_df["wiki_link"] = top_animals_df["ScientificName"].apply(
    lambda name: f"https://en.wikipedia.org/wiki/{urllib.parse.quote(name.replace(' ', '_'))}"
)

# Display result
top_animals_df

,CommonName,ScientificName,occurrenceCount,wiki_link
0,"Rabbit, European Rabbit",Oryctolagus cuniculus,5754,https://en.wikipedia.org/wiki/Oryctolagus_cuni...
1,"Red Fox, Fox",Vulpes vulpes,5485,https://en.wikipedia.org/wiki/Vulpes_vulpes
2,Koala,Phascolarctos cinereus,4897,https://en.wikipedia.org/wiki/Phascolarctos_ci...
3,Eastern Grey Kangaroo,Macropus giganteus,3734,https://en.wikipedia.org/wiki/Macropus_giganteus
4,Swamp Wallaby,Wallabia bicolor,3199,https://en.wikipedia.org/wiki/Wallabia_bicolor
5,Short-beaked Echidna,Tachyglossus aculeatus,2894,https://en.wikipedia.org/wiki/Tachyglossus_acu...
6,Western Grey Kangaroo,Macropus fuliginosus,2280,https://en.wikipedia.org/wiki/Macropus_fuligin...
7,"Bare-nosed Wombat, Common Wombat",Vombatus ursinus,1856,https://en.wikipedia.org/wiki/Vombatus_ursinus
8,Platypus,Ornithorhynchus anatinus,1337,https://en.wikipedia.org/wiki/Ornithorhynchus_...
9,Southern Long-nosed Bandicoot,Perameles nasuta,1267,https://en.wikipedia.org/wiki/Perameles_nasuta
10,Greater Bilby,Macrotis lagotis,1120,https://en.wikipedia.org/wiki/Macrotis_lagotis
11,Gang-gang Cockatoo,Callocephalon fimbriatum,1025,https://en.wikipedia.org/wiki/Callocephalon_fi...
12,Agile Antechinus,Antechinus agilis,690,https://en.wikipedia.org/wiki/Antechinus_agilis
13,Bush Stone-curlew,Burhinus grallarius,671,https://en.wikipedia.org/wiki/Burhinus_grallarius
14,Greater Glider (southern and central),Petauroides volans,646,https://en.wikipedia.org/wiki/Petauroides_volans
15,Yellow-footed Antechinus,Antechinus flavipes,620,https://en.wikipedia.org/wiki/Antechinus_flavipes
16,Rainbow Bee-eater,Merops ornatus,604,https://en.wikipedia.org/wiki/Merops_ornatus
17,White-bellied Sea-Eagle,Haliaeetus leucogaster,593,https://en.wikipedia.org/wiki/Haliaeetus_leuco...
18,Glossy Black-Cockatoo,Calyptorhynchus lathami,586,https://en.wikipedia.org/wiki/Calyptorhynchus_...
19,Burrowing Bettong,Bettongia lesueur,577,https://en.wikipedia.org/wiki/Bettongia_lesueur
20,Grey-headed Flying-fox,Pteropus poliocephalus,547,https://en.wikipedia.org/wiki/Pteropus_polioce...
21,Yellow-bellied Glider,Petaurus australis,478,https://en.wikipedia.org/wiki/Petaurus_australis
22,Brown Treecreeper,Climacteris picumnus,437,https://en.wikipedia.org/wiki/Climacteris_picu...
23,Flame Robin,Petroica phoenicea,414,https://en.wikipedia.org/wiki/Petroica_phoenicea
24,Pied Oystercatcher,Haematopus longirostris,397,https://en.wikipedia.org/wiki/Haematopus_longi...
25,Australian Shelduck,Tadorna tadornoides,396,https://en.wikipedia.org/wiki/Tadorna_tadornoides
26,Southern Brown Bandicoot,Isoodon obesulus,368,https://en.wikipedia.org/wiki/Isoodon_obesulus
27,Apostlebird,Struthidea cinerea,366,https://en.wikipedia.org/wiki/Struthidea_cinerea
28,Red-tailed Black-Cockatoo,Calyptorhynchus banksii,353,https://en.wikipedia.org/wiki/Calyptorhynchus_...
29,Hardhead,Aythya australis,340,https://en.wikipedia.org/wiki/Aythya_australis
30,Grey-crowned Babbler,Pomatostomus temporalis,326,https://en.wikipedia.org/wiki/Pomatostomus_tem...
31,Eastern Pygmy-possum,Cercartetus nanus,323,https://en.wikipedia.org/wiki/Cercartetus_nanus
32,Magpie Goose,Anseranas semipalmata,318,https://en.wikipedia.org/wiki/Anseranas_semipa...
33,Blue-billed Duck,Oxyura australis,313,https://en.wikipedia.org/wiki/Oxyura_australis
34,Osprey,Pandion haliaetus,302,https://en.wikipedia.org/wiki/Pandion_haliaetus
35,Cattle Egret,Bubulcus ibis,301,https://en.wikipedia.org/wiki/Bubulcus_ibis
36,Little Egret,Egretta garzetta,279,https://en.wikipedia.org/wiki/Egretta_garzetta
37,"Long-haired Rat, Mayaroo",Rattus villosissimus,270,https://en.wikipedia.org/wiki/Rattus_villosiss...
38,Pacific Gull,Larus pacificus,252,https://en.wikipedia.org/wiki/Larus_pacificus
39,White-fronted Chat,Epthianura albifrons,250,https://en.wikipedia.org/wiki/Epthianura_albif...
40,Powerful Owl,Ninox strenua,243,https://en.wikipedia.org/wiki/Ninox_strenua
41,Rufous Fantail,Rhipidura rufifrons,240,https://en.wikipedia.org/wiki/Rhipidura_rufifrons
42,Varied Sittella,Daphoenositta chrysoptera,234,https://en.wikipedia.org/wiki/Daphoenositta_ch...
43,Superb Parrot,Polytelis swainsonii,227,https://en.wikipedia.org/wiki/Polytelis_swains...
44,Squirrel Glider,Petaurus norfolcensis,220,https://en.wikipedia.org/wiki/Petaurus_norfolc...
45,Sooty Oystercatcher,Haematopus fuliginosus,210,https://en.wikipedia.org/wiki/Haematopus_fulig...
46,Comb-crested Jacana,Irediparra gallinacea,208,https://en.wikipedia.org/wiki/Irediparra_galli...
47,Little Eagle,Hieraaetus morphnoides,202,https://en.wikipedia.org/wiki/Hieraaetus_morph...
48,Tasmanian Pademelon,Thylogale billardierii,199,https://en.wikipedia.org/wiki/Thylogale_billar...
49,Diamond Firetail,Stagonopleura guttata,190,https://en.wikipedia.org/wiki/Stagonopleura_gu...
50,Wompoo Fruit-Dove,Ptilinopus magnificus,189,https://en.wikipedia.org/wiki/Ptilinopus_magni...
51,Peregrine Falcon,Falco peregrinus,172,https://en.wikipedia.org/wiki/Falco_peregrinus
52,Great Crested Grebe,Podiceps cristatus,165,https://en.wikipedia.org/wiki/Podiceps_cristatus
53,Square-tailed Kite,Lophoictinia isura,162,https://en.wikipedia.org/wiki/Lophoictinia_isura
54,Red-legged Pademelon,Thylogale stigmatica,161,https://en.wikipedia.org/wiki/Thylogale_stigma...
55,Hooded Robin,Melanodryas cucullata,153,https://en.wikipedia.org/wiki/Melanodryas_cucu...
56,Pilotbird,Pycnoptilus floccosus,153,https://en.wikipedia.org/wiki/Pycnoptilus_floc...
57,Diamond Dove,Geopelia cuneata,145,https://en.wikipedia.org/wiki/Geopelia_cuneata
58,Brush-tailed Phascogale,Phascogale tapoatafa,143,https://en.wikipedia.org/wiki/Phascogale_tapoa...
59,Black-faced Monarch,Monarcha melanopsis,136,https://en.wikipedia.org/wiki/Monarcha_melanopsis
60,Southern Cassowary,Casuarius casuarius,134,https://en.wikipedia.org/wiki/Casuarius_casuarius
61,"New Holland Mouse, Pookila",Pseudomys novaehollandiae,124,https://en.wikipedia.org/wiki/Pseudomys_novaeh...
62,Australian Bustard,Ardeotis australis,113,https://en.wikipedia.org/wiki/Ardeotis_australis
63,Grey Goshawk,Accipiter novaehollandiae,110,https://en.wikipedia.org/wiki/Accipiter_novaeh...
64,Feathertail Glider,Acrobates pygmaeus,109,https://en.wikipedia.org/wiki/Acrobates_pygmaeus
65,Kelp Gull,Larus dominicanus,106,https://en.wikipedia.org/wiki/Larus_dominicanus
66,Turquoise Parrot,Neophema pulchella,105,https://en.wikipedia.org/wiki/Neophema_pulchella
67,Long-nosed Potoroo,Potorous tridactylus,96,https://en.wikipedia.org/wiki/Potorous_tridact...
68,"Little Bent-winged Bat, Little Bent-wing Bat",Miniopterus australis,93,https://en.wikipedia.org/wiki/Miniopterus_aust...
69,Southern Whiteface,Aphelocephala leucopsis,88,https://en.wikipedia.org/wiki/Aphelocephala_le...
70,White-winged Triller,Lalage tricolor,88,https://en.wikipedia.org/wiki/Lalage_tricolor
71,"Large-eared Pied Bat, Large Pied Bat",Chalinolobus dwyeri,87,https://en.wikipedia.org/wiki/Chalinolobus_dwyeri
72,Long-footed Potoroo,Potorous longipes,83,https://en.wikipedia.org/wiki/Potorous_longipes
73,"Spotted-tailed Quoll, Tiger Quol",Dasyurus maculatus,80,https://en.wikipedia.org/wiki/Dasyurus_maculatus
74,Red-necked Stint,Calidris ruficollis,79,https://en.wikipedia.org/wiki/Calidris_ruficollis
75,Eastern Horseshoe-bat,Rhinolophus megaphyllus,78,https://en.wikipedia.org/wiki/Rhinolophus_mega...
76,Rose-crowned Fruit-Dove,Ptilinopus regina,78,https://en.wikipedia.org/wiki/Ptilinopus_regina
77,Olive Whistler,Pachycephala olivacea,76,https://en.wikipedia.org/wiki/Pachycephala_oli...
78,Spotted Harrier,Circus assimilis,76,https://en.wikipedia.org/wiki/Circus_assimilis
79,"Long-nosed Fur-seal, New Zealand Fur-seal",Arctocephalus forsteri,75,https://en.wikipedia.org/wiki/Arctocephalus_fo...
80,Southern Emu-wren,Stipiturus malachurus,74,https://en.wikipedia.org/wiki/Stipiturus_malac...
81,Bar-tailed Godwit,Limosa lapponica,71,https://en.wikipedia.org/wiki/Limosa_lapponica
82,Leadbeater's Possum,Gymnobelideus leadbeateri,71,https://en.wikipedia.org/wiki/Gymnobelideus_le...
83,Pink Robin,Petroica rodinogaster,71,https://en.wikipedia.org/wiki/Petroica_rodinog...
84,Swift Parrot,Lathamus discolor,70,https://en.wikipedia.org/wiki/Lathamus_discolor
85,Malleefowl,Leipoa ocellata,69,https://en.wikipedia.org/wiki/Leipoa_ocellata
86,Sooty Owl,Tyto tenebricosa,69,https://en.wikipedia.org/wiki/Tyto_tenebricosa
87,White-throated Needletail,Hirundapus caudacutus,69,https://en.wikipedia.org/wiki/Hirundapus_cauda...
88,"Bridled Nail-tail Wallaby, Bridled Nailtail Wa...",Onychogalea fraenata,65,https://en.wikipedia.org/wiki/Onychogalea_frae...
89,Blue-winged Parrot,Neophema chrysostoma,64,https://en.wikipedia.org/wiki/Neophema_chrysos...
90,Little Penguin,Eudyptula minor,63,https://en.wikipedia.org/wiki/Eudyptula_minor
91,Crested Bellbird,Oreoica gutturalis,62,https://en.wikipedia.org/wiki/Oreoica_gutturalis
92,Eastern Barred Bandicoot,Perameles gunnii,62,https://en.wikipedia.org/wiki/Perameles_gunnii
93,Satin Flycatcher,Myiagra cyanoleuca,62,https://en.wikipedia.org/wiki/Myiagra_cyanoleuca
94,"Australian Fur-seal, Australo-African Fur-seal",Arctocephalus pusillus,61,https://en.wikipedia.org/wiki/Arctocephalus_pu...
95,"Pale Field-rat, Djini",Rattus tunneyi,61,https://en.wikipedia.org/wiki/Rattus_tunneyi
96,Brush-tailed Rock-wallaby,Petrogale penicillata,59,https://en.wikipedia.org/wiki/Petrogale_penici...
97,Plains-wanderer,Pedionomus torquatus,58,https://en.wikipedia.org/wiki/Pedionomus_torqu...
98,Humpback Whale,Megaptera novaeangliae,57,https://en.wikipedia.org/wiki/Megaptera_novaea...
99,Rufous Bettong,Aepyprymnus rufescens,57,https://en.wikipedia.org/wiki/Aepyprymnus_rufe...
100,Spectacled Flying-fox,Pteropus conspicillatus,57,https://en.wikipedia.org/wiki/Pteropus_conspic...
101,White-footed Dunnart,Sminthopsis leucopus,56,https://en.wikipedia.org/wiki/Sminthopsis_leuc...
102,Barking Owl,Ninox connivens,55,https://en.wikipedia.org/wiki/Ninox_connivens
103,"Common Greenshank, Greenshank",Tringa nebularia,55,https://en.wikipedia.org/wiki/Tringa_nebularia
104,Black-faced Cormorant,Phalacrocorax fuscescens,54,https://en.wikipedia.org/wiki/Phalacrocorax_fu...
105,Squatter Pigeon,Geophaps scripta,54,https://en.wikipedia.org/wiki/Geophaps_scripta
106,"Latham's Snipe, Japanese Snipe",Gallinago hardwickii,53,https://en.wikipedia.org/wiki/Gallinago_hardwi...
107,Southern Scrub-robin,Drymodes brunneopygia,51,https://en.wikipedia.org/wiki/Drymodes_brunneo...
108,"Kowari, brushy-tailed marsupial rat, Byrne's c...",Dasyuroides byrnei,50,https://en.wikipedia.org/wiki/Dasyuroides_byrnei
109,"Large-footed Myotis, Southern Myotis",Myotis macropus,50,https://en.wikipedia.org/wiki/Myotis_macropus
110,Australasian Gannet,Morus serrator,48,https://en.wikipedia.org/wiki/Morus_serrator
111,Eastern Bristlebird,Dasyornis brachypterus,48,https://en.wikipedia.org/wiki/Dasyornis_brachy...
112,Masked Owl,Tyto novaehollandiae,48,https://en.wikipedia.org/wiki/Tyto_novaehollan...
113,"Brush-tailed Bettong, Woylie",Bettongia penicillata,47,https://en.wikipedia.org/wiki/Bettongia_penici...
114,Gould's Long-eared Bat,Nyctophilus gouldi,47,https://en.wikipedia.org/wiki/Nyctophilus_gouldi
115,Rufous Scrub-bird,Atrichornis rufescens,44,https://en.wikipedia.org/wiki/Atrichornis_rufe...
116,Common Sandpiper,Actitis hypoleucos,43,https://en.wikipedia.org/wiki/Actitis_hypoleucos
117,Double-eyed Fig-Parrot,Cyclopsitta diophthalma,43,https://en.wikipedia.org/wiki/Cyclopsitta_diop...
118,Sharp-tailed Sandpiper,Calidris acuminata,43,https://en.wikipedia.org/wiki/Calidris_acuminata
119,Purple-gaped Honeyeater,Lichenostomus cratitius,42,https://en.wikipedia.org/wiki/Lichenostomus_cr...
120,"Red-tailed Phascogale, Red-tailed Wambenger, K...",Phascogale calura,42,https://en.wikipedia.org/wiki/Phascogale_calura
121,Striated Fieldwren,Calamanthus fuliginosus,42,https://en.wikipedia.org/wiki/Calamanthus_fuli...
122,Whiskered Tern,Chlidonias hybrida,42,https://en.wikipedia.org/wiki/Chlidonias_hybrida
123,Curlew Sandpiper,Calidris ferruginea,41,https://en.wikipedia.org/wiki/Calidris_ferruginea
124,Black-necked Stork,Ephippiorhynchus asiaticus,40,https://en.wikipedia.org/wiki/Ephippiorhynchus...
125,Spotted Bowerbird,Chlamydera maculata,39,https://en.wikipedia.org/wiki/Chlamydera_maculata
126,"Australian Sea-lion, Australian Sea Lion",Neophoca cinerea,38,https://en.wikipedia.org/wiki/Neophoca_cinerea
127,Ruddy Turnstone,Arenaria interpres,37,https://en.wikipedia.org/wiki/Arenaria_interpres
128,Lewin's Rail,Lewinia pectoralis,34,https://en.wikipedia.org/wiki/Lewinia_pectoralis
129,Pacific Golden Plover,Pluvialis fulva,34,https://en.wikipedia.org/wiki/Pluvialis_fulva
130,"Hastings River Mouse, Koontoo",Pseudomys oralis,33,https://en.wikipedia.org/wiki/Pseudomys_oralis
131,Redthroat,Pyrrholaemus brunneus,32,https://en.wikipedia.org/wiki/Pyrrholaemus_bru...
132,Shy Heathwren,Hylacola cauta,32,https://en.wikipedia.org/wiki/Hylacola_cauta
133,Rufous Bristlebird,Dasyornis broadbenti,31,https://en.wikipedia.org/wiki/Dasyornis_broadb...
134,"Tasmanian Bettong, Eastern Bettong",Bettongia gaimardi,31,https://en.wikipedia.org/wiki/Bettongia_gaimardi
135,Whimbrel,Numenius phaeopus,31,https://en.wikipedia.org/wiki/Numenius_phaeopus
136,"Eastern Curlew, Far Eastern Curlew",Numenius madagascariensis,30,https://en.wikipedia.org/wiki/Numenius_madagas...
137,Barred Cuckoo-shrike,Coracina lineata,29,https://en.wikipedia.org/wiki/Coracina_lineata
138,Black Falcon,Falco subniger,28,https://en.wikipedia.org/wiki/Falco_subniger
139,Southern Right Whale,Eubalaena australis,27,https://en.wikipedia.org/wiki/Eubalaena_australis
140,Double-banded Plover,Charadrius bicinctus,25,https://en.wikipedia.org/wiki/Charadrius_bicin...
141,Numbat,Myrmecobius fasciatus,25,https://en.wikipedia.org/wiki/Myrmecobius_fasc...
142,Black-breasted Buzzard,Hamirostra melanosternon,24,https://en.wikipedia.org/wiki/Hamirostra_melan...
143,Cotton Pygmy-goose,Nettapus coromandelianus,24,https://en.wikipedia.org/wiki/Nettapus_coroman...
144,"Broad-toothed Rat, Tooarrana",Mastacomys fuscus,23,https://en.wikipedia.org/wiki/Mastacomys_fuscus
145,"Marsh Sandpiper, Little Greenshank",Tringa stagnatilis,23,https://en.wikipedia.org/wiki/Tringa_stagnatilis
146,"Pale-vented Bush-hen, Bush-hen",Amaurornis moluccana,23,https://en.wikipedia.org/wiki/Amaurornis_moluc...
147,Quokka,Setonix brachyurus,23,https://en.wikipedia.org/wiki/Setonix_brachyurus
148,Black Noddy,Anous minutus,22,https://en.wikipedia.org/wiki/Anous_minutus
149,"Indian Ocean Bottlenose Dolphin, Spotted Bottl...",Tursiops aduncus,22,https://en.wikipedia.org/wiki/Tursiops_aduncus
150,Western Pygmy-possum,Cercartetus concinnus,22,https://en.wikipedia.org/wiki/Cercartetus_conc...
151,Terek Sandpiper,Xenus cinereus,20,https://en.wikipedia.org/wiki/Xenus_cinereus
152,Yellow-bellied Sheathtail-bat,Saccolaimus flaviventris,20,https://en.wikipedia.org/wiki/Saccolaimus_flav...
153,Albert's Lyrebird,Menura alberti,19,https://en.wikipedia.org/wiki/Menura_alberti
154,"Eastern Falsistrelle, Eastern False Pipistrelle",Falsistrellus tasmaniensis,19,https://en.wikipedia.org/wiki/Falsistrellus_ta...
155,Great Knot,Calidris tenuirostris,19,https://en.wikipedia.org/wiki/Calidris_tenuiro...
156,Greater Broad-nosed Bat,Scoteanax rueppellii,19,https://en.wikipedia.org/wiki/Scoteanax_rueppe...
157,Poonta,Pseudomys bolami,19,https://en.wikipedia.org/wiki/Pseudomys_bolami
158,White-browed Treecreeper,Climacteris affinis,19,https://en.wikipedia.org/wiki/Climacteris_affinis
159,Chestnut-rumped Heathwren,Hylacola pyrrhopygia,18,https://en.wikipedia.org/wiki/Hylacola_pyrrhop...
160,"Mitchell's Hopping-mouse, Pankot",Notomys mitchellii,18,https://en.wikipedia.org/wiki/Notomys_mitchellii
161,Red-backed Button-quail,Turnix maculosus,18,https://en.wikipedia.org/wiki/Turnix_maculosus
162,Australasian Bittern,Botaurus poiciloptilus,17,https://en.wikipedia.org/wiki/Botaurus_poicilo...
163,Chestnut Quail-thrush,Cinclosoma castanotum,17,https://en.wikipedia.org/wiki/Cinclosoma_casta...
164,Superb Fruit-Dove,Ptilinopus superbus,17,https://en.wikipedia.org/wiki/Ptilinopus_superbus
165,Collared Kingfisher,Todiramphus chloris,16,https://en.wikipedia.org/wiki/Todiramphus_chloris
166,Eastern Ground Parrot,Pezoporus wallicus,16,https://en.wikipedia.org/wiki/Pezoporus_wallicus
167,"Eastern Quoll, Luaner",Dasyurus viverrinus,16,https://en.wikipedia.org/wiki/Dasyurus_viverrinus
168,Rufous Fieldwren,Calamanthus campestris,16,https://en.wikipedia.org/wiki/Calamanthus_camp...
169,Wood Sandpiper,Tringa glareola,16,https://en.wikipedia.org/wiki/Tringa_glareola
170,Eastern Cave Bat,Vespadelus troughtoni,15,https://en.wikipedia.org/wiki/Vespadelus_troug...
171,Mountain Pygmy-possum,Burramys parvus,15,https://en.wikipedia.org/wiki/Burramys_parvus
172,Pied Honeyeater,Certhionyx variegatus,15,https://en.wikipedia.org/wiki/Certhionyx_varie...
173,"Queensland Tube-nosed Bat, Eastern Tube-nosed Bat",Nyctimene robinsoni,15,https://en.wikipedia.org/wiki/Nyctimene_robinsoni
174,Black-tailed Godwit,Limosa limosa,14,https://en.wikipedia.org/wiki/Limosa_limosa
175,Red-lored Whistler,Pachycephala rufogularis,14,https://en.wikipedia.org/wiki/Pachycephala_ruf...
176,Flock Bronzewing,Phaps histrionica,13,https://en.wikipedia.org/wiki/Phaps_histrionica
177,Gilbert's Whistler,Pachycephala inornata,13,https://en.wikipedia.org/wiki/Pachycephala_ino...
178,Lemuroid Ringtail Possum,Hemibelideus lemuroides,13,https://en.wikipedia.org/wiki/Hemibelideus_lem...
179,Sanderling,Calidris alba,13,https://en.wikipedia.org/wiki/Calidris_alba
180,Stripe-faced Dunnart,Sminthopsis macroura,13,https://en.wikipedia.org/wiki/Sminthopsis_macr...
181,Banded Stilt,Cladorhynchus leucocephalus,12,https://en.wikipedia.org/wiki/Cladorhynchus_le...
182,Fluttering Shearwater,Puffinus gavia,12,https://en.wikipedia.org/wiki/Puffinus_gavia
183,"Red Knot, Knot",Calidris canutus,12,https://en.wikipedia.org/wiki/Calidris_canutus
184,White Tern,Gygis alba,12,https://en.wikipedia.org/wiki/Gygis_alba
185,Buff-sided Robin,Poecilodryas cerviniventris,11,https://en.wikipedia.org/wiki/Poecilodryas_cer...
186,Fork-tailed Swift,Apus pacificus,11,https://en.wikipedia.org/wiki/Apus_pacificus
187,"Oriental Plover, Oriental Dotterel",Charadrius veredus,11,https://en.wikipedia.org/wiki/Charadrius_veredus
188,Oriental Pratincole,Glareola maldivarum,11,https://en.wikipedia.org/wiki/Glareola_maldivarum
189,Palm Cockatoo,Probosciger aterrimus,11,https://en.wikipedia.org/wiki/Probosciger_ater...
190,Striated Grasswren,Amytornis striatus,11,https://en.wikipedia.org/wiki/Amytornis_striatus
191,Common Noddy,Anous stolidus,10,https://en.wikipedia.org/wiki/Anous_stolidus
192,"Eastern Blossom Bat, Queensland Blossom Bat",Syconycteris australis,10,https://en.wikipedia.org/wiki/Syconycteris_aus...
193,Golden-tipped Bat,Phoniscus papuensis,10,https://en.wikipedia.org/wiki/Phoniscus_papuensis
194,Red-chested Button-quail,Turnix pyrrhothorax,10,https://en.wikipedia.org/wiki/Turnix_pyrrhothorax
195,Common Tern,Sterna hirundo,9,https://en.wikipedia.org/wiki/Sterna_hirundo
196,Eastern Grass Owl,Tyto longimembris,9,https://en.wikipedia.org/wiki/Tyto_longimembris
197,"Lesser Frigatebird, Least Frigatebird",Fregata ariel,9,https://en.wikipedia.org/wiki/Fregata_ariel
198,Marbled Frogmouth,Podargus ocellatus,9,https://en.wikipedia.org/wiki/Podargus_ocellatus
199,Red-tailed Tropicbird,Phaethon rubricauda,9,https://en.wikipedia.org/wiki/Phaethon_rubricauda
200,Black Bittern,Ixobrychus flavicollis,8,https://en.wikipedia.org/wiki/Ixobrychus_flavi...
201,"Eastern Chestnut Mouse, Karrooka",Pseudomys gracilicaudatus,8,https://en.wikipedia.org/wiki/Pseudomys_gracil...
202,"Oriental Cuckoo, Horsfield's Cuckoo",Cuculus optatus,8,https://en.wikipedia.org/wiki/Cuculus_optatus
203,Purple-crowned Fairy-wren,Malurus coronatus,8,https://en.wikipedia.org/wiki/Malurus_coronatus
204,Radjah Shelduck,Tadorna radjah,8,https://en.wikipedia.org/wiki/Tadorna_radjah
205,Blue-faced Parrot-Finch,Erythrura trichroa,7,https://en.wikipedia.org/wiki/Erythrura_trichroa

In [45]:
top_animals_df.to_csv("top_animals_by_occ_wikilink")